Add Django and FxA
mozilla-services/privacy-pack pull request #1
Opened 2021-07-28 18:30 UTC by say-yawn

Includes basic setup from Django and sign-in and our using SocialAccount FxA

2021-07-28 20:26 UTC, groovecoder requested changes

2021-07-28 20:26 UTC, groovecoder commented on README.md
> +3. Install Pyhton and Node requirements:
```suggestion
3. Install Python requirements:
```

2021-07-28 20:26 UTC, groovecoder commented on README.md
> +    SECRET_KEY=secret-key-should-be-different-for-every-install
👍

2021-07-28 20:26 UTC, groovecoder commented on README.md
> +superuser account you created above, and add a social app for Firefox Accounts:
nit: You'll have to sign in with the superuser account to complete step 3 before this.

2021-07-28 20:26 UTC, groovecoder commented on README.md
> +   * Name: oauth-stable.dev.lcip.org
We're trying to get away from using the `stable` FXA server. Can we change this to the FXA `stage` environment?

2021-07-28 20:26 UTC, groovecoder commented on privacypack/settings.py
> +)
not blocking but curious: can we disable these password validators and the django auth `ModelBackend` when `ADMIN_ENABLED` is `False`? Might be tighter security.

2021-07-28 20:26 UTC, groovecoder commented on requirements.txt
> +PyFxA==0.7.7
Are we actually using this module?

2021-07-28 20:26 UTC, groovecoder commented on privacypack/asgi.py
> +application = get_asgi_application()
Do we need to include this file if we're using `wsgi` instead?

2021-08-03 15:37 UTC, say-yawn commented on README.md
> +    SECRET_KEY=secret-key-should-be-different-for-every-install
_don't commit secrets_ 😭 😆

2026-05-13 23:04 UTC, closed without merging